- name: Start traefik:v1.7-alpine container
  community.docker.docker_container:
    name: traefik_alpine
    image: traefik:v1.7-alpine
    state: started
    ports:
      - "8080:80"
    restart_policy: no
